### ISSUE TITLE
gulp-inject running very slow

### ISSUE THREAD

**Issue by ericmarcos** [klei/gulp-inject#58]
I'm using the [gulp-angular yeoman generator](https://www.npmjs.org/package/generator-gulp-angular) which uses gulp-inject in the `build` task (actually, the `html` task) like this:

```
gulp.src('app/*.html')
.pipe($.inject(gulp.src('.tmp/partials/**/*.js'), {
      read: false,
      starttag: '<!-- inject:partials -->',
      addRootSlash: false,
      addPrefix: '../'
    }))
```

There are just 2 html files with inject templates and only one js file and it takes more than 7 seconds to execute this part of the task. Any hints?

**Comment by codeofsumit** [comment]
does it improve speed? It runs very slow locally (same problem) and tortoise like on our deployment server

**Comment by joakimbeng** [comment]
@codeofsumit It doesn't hurt to be a little helpful... How do you expect me to investigate this further without any information at all?

I don't think the issue is caused by this plugin though, it runs all its tests (164) in about one ms per test which does a lot more injections than the project that @ericmarcos is talking about. The problem could be caused by gulp itself, or gulp.src or anything else for that matter because I don't know how your code looks like.

**Comment by xnuter** [comment]
I had the same issue. But finally I found out that `gulp-inject`is not slow. See the solution here: http://stackoverflow.com/questions/34190812/troubleshooting-slow-gulp-inject/36964105#36964105
