### ISSUE TITLE
single quotes get replaced with &apos; when injecting in html

### ISSUE THREAD

**Issue by sergproua** [klei/gulp-inject#85]
When run inject on html files single quotes inside property values get replaced with &amp;apos; even when outside the injection tags. 

```
<div data-ng-include="'somewhere/something.html'"/>
becomes
<div data-ng-include="&apos;somewhere/something.html&apos;"/>
```

Is there an option to prevent that?

**Comment by joakimbeng** [comment]
> @sergproua "..even when outside the injection tags.."

I think that is evidence enough that it's not `gulp-inject` that's causing the quote replacement but something else. How does your gulp task look like?

Is it really a problem anyway? Does the ng-include not work with those entities inside the attribute? (I know I for one use `ng-if="condition1 &amp;&amp; condition2"` instead of plain `&&` to make htmllint happy)

**Comment by sergproua** [comment]
you're right, i was able to recreate the problem, gulp-rev-mtime was causing the issue.

```
gulp.task('html-apos-issue', function () {
    var angularAppJs = gulp.src(["./app/**/*module.js", "./app/**/*.js"], { read: false });
    return gulp.src('./index-test.html')
        .pipe(inject(angularAppJs, { starttag: '<!-- inject:angular:js -->', relative: true }))
        .pipe(revmtime()) // <----bugger!
        .pipe(rename('./index-test-out.html'))
        .pipe(gulp.dest('.'));
});
```
