### ISSUE TITLE
using npm package management

### ISSUE THREAD

**Issue by joshikeerti** [klei/gulp-inject#99]
If I am using bower for some packages and npm for some packages, what's the best way to handle it? I am using main-bower-files for my bower packages. As for the node packages how should they be used?

**Comment by joakimbeng** [comment]
Hmm, I don't think there is a good way to do this at the moment, other than using Browserify or Webpack to bundle your frontend application into one file and inject only that.
Because one can not determine which packages that are solely used in backend and exclude them before injecting, if not using the above mentioned packaged.

See http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging and http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm for good reads on this topic.
